### ISSUE TITLE
【每日前端】表格及其相关样式与布局

### ISSUE THREAD

**Issue by jctang1202** [jctang1202/blog#10]
### 表格相关标签

- table
- tr、th、 td
- thead、tbody、tfoot
- caption、col、colgroup

```html

<table>
  <caption></caption>
  <colgroup>
      <col>
      <col>
  </colgroup>
  <thead>
    <tr>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tfoot>
    <tr>
      <td></td>
      <td></td>
    </tr>
  </tfoot>
  <tbody>
    <tr>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td></td>
      <td></td>
    </tr>
  </tbody>
</table>

```

table-layout | CSS-Tricks
https://css-tricks.com/almanac/properties/t/table-layout/

display | CSS-Tricks
https://css-tricks.com/almanac/properties/d/display/

### table 标签

```css
table {

  table-layout: fixed; 

}
```

> - auto：自动布局，__列的宽度__是由列单元格中__没有折行的最宽的内容__设定的
> - fixed：固定布局，__列的宽度__取决于__表格宽度、列宽度、表格边框宽度、单元格间距__，而与单元格的内容无关，与自动布局相比，浏览器可以更快得对表格进行布局。

> 默认如果不设置 table 及列的宽度，不论使用什么布局，table的宽度及列的宽度都由内容撑开。

> 而如果对 table 设置一个宽度，如“100%”，则列宽度存在以下几种情况：
> - 没有任何列设置宽度，则列的宽度由其内容按比例分配
> - 如果有某一列或几列设置了宽度，则剩余的由其内容按比例分配
> - 如果每列都设置了宽度，每列的宽度加起来不等于table的宽度，则按照列设置的宽度比例重新分配宽度，而不是实际列设置的宽度

>如果在设置 table 宽度的前提下，再设置其为固定布局，则列宽度存在以下几种情况：
> - 没有任何列设置宽度，则宽度等分
> - 如果有某一列或几列设置了宽度，则剩余的宽度等分
> - 如果每列都设置了宽度，则按设置的比例分配宽度

#### 适用于表格的样式

```css
table, th, td {

  border: 1px solid #ccc; /* 边框样式 */

}

table {
  
  border-spacing: 0; /* 边框间隙为0 */
  border-collapse: collapse; /* 边框合并 */
  border-radius: 5px; /* 圆角边框 - 但是无效 */
  
}
```

> 合并边框 `border-collapse: collapse` 和 `border-radius` 相冲

``` css
.table-radius {

  border: 1px solid #ccc; /* 整体外围边框 */
  border-radius: 5px;
  border-spacing: 0; /* 边框间隙为0 */
  border-collapse: separate; /* 边框不和合并 */
  overflow: hidden;

}

/* table 已经完成整体外围的边框，那里面格子的边框就由 th 和 td 来拼成*/
.table-radius th,
.table-radius td {

  border-bottom: 1px solid #f00; /* 设置为红色，以区别 table 的边框 */
  border-right: 1px solid #f00;

}

/* 最后一列单元格的右边框与最后一排单元格的下边框需要去掉 */
.table-radius th:last-child,
.table-radius td:last-child {

  border-right: 0;

}

.table-radius tr:last-child td{

  border-bottom: 0;

}
```

![2017-09-29-10-26-49](https://user-images.githubusercontent.com/19782901/31988060-60a399a6-b9a0-11e7-9fec-3a62254937b7.png)

http://layout.imweb.io/article/table.html

#### border-collapse

> - separate 边框会被分开，不会忽略 border-spacing 和 empty-cells 属性。
> - collapse 如果可能，边框会合并为一个单一的边框。会忽略 border-spacing 和 empty-cells 属性。

#### 其它

```css

table {
  empty-cells: show;
}

```

> The empty-cells property in CSS selects empty table cells for the purpose of **specifying whether or not to display borders and backgrounds on them.**  It's kind of like applying a visibility property on empty table cells.

https://css-tricks.com/almanac/properties/e/empty-cells/

#### colgroup 和 col 

两种作用差不多，可以决定列的样式和类，前者可以包含后者，使用 `span` 属性来指定列数。
http://www.runoob.com/try/try.php?filename=tryhtml_col_test

### td & th

`colspan` 和 `rowspan ` 用来合并单元格。
