### ISSUE TITLE
【每日前端】CSS Grid 

### ISSUE THREAD

**Issue by jctang1202** [jctang1202/blog#5]
### CSS Grid 

浏览器支持：
https://caniuse.com/#search=grid 

半个小时了解完：
https://www.youtube.com/watch?v=jV8B24rSN5o
https://developer.mozilla.org/zh-CN/docs/Web/CSS/CSS_Grid_Layout

`CSS Grid` 可以控制两个方向，而 `Flexbox` 只能可以控制一个方向 。跟 `Flexbox` 一样，划分 `Grid Container` 和 `Grid Items` 。

https://css-tricks.com/snippets/css/complete-guide-grid/

#### 术语 

- Grid Container 
- Grid Items 
- Grid Line
- Grid Track 
- Grid Area 
- Grid Cell

#### 属性

```css

.container {
  display: grid | inline-grid | subgrid;
}

.container {
  grid-template-columns: <track-size> ... | <line-name> <track-size> ...;
  grid-template-rows: <track-size> ... | <line-name> <track-size> ...;
}

```
`<line-name>` 相对比较灵活一点，因为同一条 Grid Line 可能有几个名称。

https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template-columns
https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template-rows
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Line-based_Placement_with_CSS_Grid
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Layout_using_Named_Grid_Lines

`fr` 引入了一个新的 Unit ，它的作用跟 `flex-grow` 差不多。对剩余的空间进行分配。

`grid-template-areas` 和 `grid-area` 配合使用。前者适用于 Container ，后者适用于 Items。

网格设置 `grid-template` : 
- `grid-template-columns` 
- `grid-template-rows`
- `grid-template-areas` 网格合并方式

网格之间的间隙 `grid-gap` :
- `grid-column-gap`
- `grid-row-gap` 

网格对齐方式
`justify-items`
`align-items`
`justify-content`
`align-content`

隐形网格设置
`grid-auto-columns`
`grid-auto-rows`

网格合并 
`grid-column` 
- `grid-column-start`
- `grid-column-end`

`grid-row`
- `grid-row-start`
- `grid-row-end`

`grid-area`

网格流：
`grid-auto-flow`

网格单元自我内部对齐
`align-self`
`justify-self`
